permalink: pretty

theme: jekyll_patternbot

patternbot:
  title: "Melissa Lees"
  description: |
    A pattern library for Melissa Lees' portfolio website.
  font_url: "https://use.typekit.net/sdu8rvp.css"
  rationales:
    typefaces.primary:  |
      Korolev was chosen for my portfolio because it has an awesome bold and unified feel. It is modern in feel, but still has characteristics of great traditionally strong fonts.
collections:
  pieces:
    output: true

defaults:
  - scope:
      path: _pieces
    values:
      layout: pieces
