title: "Buttons"
description: |
The buttons are one of the only elements on the page using the bright orange colour. This makes them stand out and are unique against the turquoise background.

patterns:
  basic:
    title: "Basic"
    description: |
    The basic buttons are bright orange with rounded corners. The colour contrasts well as it compliments the turquoise colour.
    width: "12em"

    ghost:
      title: "Ghost"
      description: |
      The ghost button is will be for banners and busier image cards. It has a lighter colour orange than the regular buttons.
      background: "--color-primary-light"

      light:
        fields:
          - name: text
          type: string
          example: "See collection"
          - name: url
          type: url
          example: "/bath-bomb"
