title: "Buttons"
description: |
  Buttons will be used sparingly throughout my website to keep it clean and organized.

patterns:
  basic:
    title: "Basic"
    description: |
    This button will be used on the home page to view specific portfolio pieces.
    width: "12em"

    pages:
      title: "Pages"
      description: |
      This button will be used on the contact pages.
      background: "--color-primary-light"
      fields:
      - name: data
        type: object
        data:
          source: "site.pieces[0]"
          type: piece

      light:
        fields:
          - name: text
          type: string
          example: "See collection"
          - name: url
          type: url
          example: "/ashley-hair-design"
